# 服务端口
server:
  port: 8085
  servlet:
    context-path: "/fms"
# 配置数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fms?useUnicode=true&characterEncoding=UTF-8&severTimeZone=UTC
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl